name: feature 브랜치 전용 S3 버킷 상태 관리

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - dev

jobs:
  cd-feat:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # 프로젝트에서 사용하는 Node.js 버전에 맞게 설정

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn run build # Vite로 프로젝트를 빌드

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Determine S3 bucket name with branch name
        id: extract-bucket-name
        env:
          FEATURE_BRANCH: ${{ github.head_ref }}
        run: |
          # feat/ 이후의 문자열만 추출, empty string일 경우 exit
          BUCKET_NAME=$(echo $FEATURE_BRANCH | sed 's|^feat/||')
          if [ -z "$BUCKET_NAME" ]; then
            echo "Bucket name is not set properly. Exiting."
            exit 1
          fi
          echo "Bucket name determined: $BUCKET_NAME" # For debugging

      - name: Create Bucket
        continue-on-error: true
        run: |
          aws s3api create-bucket --bucket $S3_BUCKET --region ap-northeast-2 --create-bucket-configuration LocationConstraint=ap-northeast-2

      - name: Handle Build Deployment and S3 Buckets
        env:
          S3_BUCKET: zipline-fe-${{ env.BUCKET_NAME }}
        run: |
          if [ "${{ github.event.action }}" = "opened" ]; then
            echo "Set S3 bucket config: $S3_BUCKET"

            aws s3api delete-public-access-block --bucket $S3_BUCKET
            
            aws s3api put-bucket-policy --bucket $S3_BUCKET --policy '{
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Principal": "*",
                  "Action": "s3:GetObject",
                  "Resource": "arn:aws:s3:::'$S3_BUCKET'/*"
                }
              ]
            }'

            aws s3 website $S3_BUCKET --index-document index.html --error-document index.html

            aws s3 sync ./dist s3://$S3_BUCKET/ --delete

          elif [ "${{ github.event.action }}" = "reopened" ] || [ "${{ github.event.action }}" = "synchronize" ]; then
            echo "Sync local job and S3 bucket: $S3_BUCKET"
            aws s3 sync ./dist s3://$S3_BUCKET/ --delete
          elif [ "${{ github.event.action }}" = "closed" ] && [ "${{ github.event.pull_request.merged }}" = "true" ]; then
            echo "Deleting S3 bucket: $S3_BUCKET"
            aws s3 rm s3://$S3_BUCKET --recursive
            aws s3 rb s3://$S3_BUCKET --force
          else
            echo "No action needed"
          fi
