name: Build and Upload to S3

on:
  push:
    branches:
      - main

jobs:
  upload-to-s3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # 프로젝트에서 사용하는 Node.js 버전에 맞게 설정

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn run build # Vite로 프로젝트를 빌드

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload build folder to S3
        run: aws s3 sync ./build s3://zipline-frontend/ --delete
