name: PR에 Feature 브랜치 주소 코멘트 추가

on:
  workflow_call:
    inputs:
      content:
        required: true
        type: string
      pr_number:
        required: true
        type: number

jobs:
  s3_address:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: comment PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: ${{inputs.content}}
          pr-number: ${{ inputs.pr_number}}
